mongodb:
    link: mongodb://mongo_rss_spider:27017  # mongodb://172.17.0.16:27017 mongodb://localhost:27023
rsshub:
    # replace https://rsshub.app
    host: http://rsshub_diygod:1200/  # http://172.17.0.15:1200/  http://localhost:1202/
rss:
    zhihu_hotlist:
        link: https://rsshub.app/zhihu/hotlist
        key_list:
            - title
            - link
            - published
            - author
            - summary
    smzdm_feed:
        link: http://feed.smzdm.com
        key_list:
            - title
            - link
            - published
            - focus_pic
            - summary
    smzdm_haitao:
        link: http://haitao.smzdm.com/feed
        key_list:
            - title
            - link
            - published
            - focus_pic
            - summary
    smzdm_post:
        link: http://post.smzdm.com/feed
        key_list:
            - title
            - link
            - published
            - author
            - summary
    smzdm_faxian:
        link: http://faxian.smzdm.com/feed
        key_list:
            - title
            - link
            - published
            - focus_pic
            - summary
    smzdm_news:
        link: http://news.smzdm.com/feed
        key_list:
            - title
            - link
            - published
            - author
            - summary