mongodb:
    link: mongodb://localhost:27023
rss:
    zhihu_hotlist:
        link: https://rsshub.app/zhihu/hotlist
        key_list:
            - title
            - summary
            - published
            - link
            - author