mongodb:
    link: mongodb://172.17.0.16:27017  #  mongodb://172.17.0.16:27017 mongodb://localhost:27023
rsshub:
    # replace https://rsshub.app
    host: http://172.17.0.15:1200/  # http://172.17.0.15:1200/  http://localhost:1202/
rss:
    zhihu_hotlist:
        link: https://rsshub.app/zhihu/hotlist
        key_list:
            - title
            - summary
            - published
            - link
            - author