name: Publish Docker
on:
  # Trigger the workflow on push,
  # but only for the master branch
  push:
    branches:
      - master
      - development
jobs:
  docker_build_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: neutrino3316/rss_spider
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
