name: Update DockerHub Readme
on: push
# on:
#   # Trigger the workflow on push or pull request,
#   # but only for the master branch
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
#   # Also trigger on page_build, as well as release created events
#   page_build:
#   release:
#     types: # This configuration does not affect the page_build event above
#       - created
jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@master
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: neutrino3316/rss_spider